server:
  port: 443
  servlet:
    context-path: /Shopme
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: 123456789
    key-store-password: 123456789

spring:
  datasource:
    password: password1234
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 488725950929-j3thv1kdk95c3ftstvqnpcnjbouvlb4i.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 307503405015096
            client-secret: 977d5246ac27fb09c2f4b4e8cc12af1d
            scope:
              - email
              - public_profile
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher